fileNames: [
    '/home/elhamod/projects/taming-transformers/analysis/paca analysis/level0.csv',
    '/home/elhamod/projects/taming-transformers/analysis/paca analysis/level1.csv',
    '/home/elhamod/projects/taming-transformers/analysis/paca analysis/level2.csv',
    '/home/elhamod/projects/taming-transformers/analysis/paca analysis/level3.csv'
]

size: 256
file_list_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt"