size: 256
file_list_path:  /fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt
unique_skipped_labels: []

# file_list_path: /fastscratch/elhamod/logs/2022-11-10T02-23-40_Phylo-VQVAE-transformer256img-phase4-transformer-species-finalstronger/figs/transformer_generated_dataset/list.txt
# file_list_path: /fastscratch/elhamod/logs/2022-11-10T02-23-47_Phylo-VQVAE-transformer256img-phase4-level0-finalstronger/figs/transformer_generated_dataset/list.txt
# file_list_path: /fastscratch/elhamod/logs/2022-11-10T02-23-52_Phylo-VQVAE-transformer256img-phase4-level1-finalstronger/figs/transformer_generated_dataset/list.txt
# file_list_path: /fastscratch/elhamod/logs/2022-11-10T02-23-56_Phylo-VQVAE-transformer256img-phase4-level2-finalstronger/figs/transformer_generated_dataset/list.txt

# find /fastscratch/elhamod/logs/2022-11-10T02-23-40_Phylo-VQVAE-transformer256img-phase4-transformer-species-finalstronger/figs/transformer_generated_dataset/species -type f > /fastscratch/elhamod/logs/2022-11-10T02-23-40_Phylo-VQVAE-transformer256img-phase4-transformer-species-finalstronger/figs/transformer_generated_dataset/list.txt

# find /fastscratch/elhamod/logs/2022-11-10T02-23-47_Phylo-VQVAE-transformer256img-phase4-level0-finalstronger/figs/transformer_generated_dataset/level0 -type f  > /fastscratch/elhamod/logs/2022-11-10T02-23-47_Phylo-VQVAE-transformer256img-phase4-level0-finalstronger/figs/transformer_generated_dataset/list.txt

# find  /fastscratch/elhamod/logs/2022-11-10T02-23-52_Phylo-VQVAE-transformer256img-phase4-level1-finalstronger/figs/transformer_generated_dataset/level1 -type f  > /fastscratch/elhamod/logs/2022-11-10T02-23-52_Phylo-VQVAE-transformer256img-phase4-level1-finalstronger/figs/transformer_generated_dataset /list.txt

# find /fastscratch/elhamod/logs/2022-11-10T02-23-56_Phylo-VQVAE-transformer256img-phase4-level2-finalstronger/figs/transformer_generated_dataset/level2 -type f  > /fastscratch/elhamod/logs/2022-11-10T02-23-56_Phylo-VQVAE-transformer256img-phase4-level2-finalstronger/figs/transformer_generated_dataset/list.txt

# find /fastscratch/elhamod/logs/2022-11-08T00-00-03_Phylo-VQVAE-transformer256img-phase4-originalVQGAN/generated/1012026_100_1.0/samples_40 -type f  > /fastscratch/elhamod/logs/2022-11-08T00-00-03_Phylo-VQVAE-transformer256img-phase4-originalVQGAN/generated/1012026_100_1.0/list.txt


# file_list_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256.txt"
# size= 512
# file_list_path = "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_512.txt"



DEVICE: 0
num_workers: 8
batch_size: 1 # DO NOT CHANGE! 

per_phylo_level: True

create_histograms: True

generate_specifmen: False
save_individual_images: False
num_specimen_generated: 16

##############################

# # 256 combined nopass
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T10-40-42_Phylo-VQVAE256img-afterhyperp-combined/configs/2022-10-14T10-40-42-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T10-40-42_Phylo-VQVAE256img-afterhyperp-combined/checkpoints/last.ckpt"

# 4cbs
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/configs/2022-10-17T12-20-24-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/checkpoints/last.ckpt"

# anticlass 256
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-18T17-16-55_Phylo-VQVAE256img-afterhyperp-combined-anticlass/configs/2022-10-18T17-16-55-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-18T17-16-55_Phylo-VQVAE256img-afterhyperp-combined-anticlass/checkpoints/last.ckpt"

# 256 phylo-vqvae-phase2-morech-8cbperlevel
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-21T16-08-04_Phylo-VQVAE256img-phylo-vqvae-phase2-morech-8cbperlevel/configs/2022-10-21T16-08-04-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-21T16-08-04_Phylo-VQVAE256img-phylo-vqvae-phase2-morech-8cbperlevel/checkpoints/last.ckpt"

# 256 no phylo
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/configs/2022-10-12T10-08-53-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/checkpoints/last.ckpt"



#256 phase3-more fclayers
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-25T22-04-46_Phylo-VQVAE256img-phylo-vqvae-phase2-disentanglerconv-morefclayers/configs/2022-10-25T22-04-46-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-25T22-04-46_Phylo-VQVAE256img-phylo-vqvae-phase2-disentanglerconv-morefclayers/checkpoints/last.ckpt"

# # multiclass
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-multiclass-phase4/configs/2022-10-28T19-59-33-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-multiclass-phase4/checkpoints/epoch=000104.ckpt"

# multilabel
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-phase4/configs/2022-10-28T19-59-33-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-phase4/checkpoints/epoch=000362.ckpt"



# # 46ch
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/configs/2022-10-14T00-55-06-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/checkpoints/last.ckpt"


# slower lr
# yaml_path: "/fastscratch/elhamod/logs/2022-10-30T20-13-25_Phylo-VQVAE256img-phase4-swapconvin-nolastrelu-multiclass-lowerlr/configs/2022-10-30T20-13-25-project.yaml"
# ckpt_path: "/fastscratch/elhamod/logs/2022-10-30T20-13-25_Phylo-VQVAE256img-phase4-swapconvin-nolastrelu-multiclass-lowerlr/checkpoints/last.ckpt"

# # *******slower lr stronganti
# ckpt_path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/checkpoints/last.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/configs/2022-10-31T12-46-01-project.yaml

# no phylo phase4
# ckpt_path: /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/checkpoints/last.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/configs/2022-11-04T15-27-23-project.yaml

# # species out
# ckpt_path: /fastscratch/elhamod/logs/2022-11-07T11-27-56_Phylo-VQVAE256img-phase5-speciesout/checkpoints/last.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-11-07T11-27-56_Phylo-VQVAE256img-phase5-speciesout/configs/2022-11-07T11-27-56-project.yaml

# # # species out
# # ckpt_path: /fastscratch/elhamod/logs/2022-11-07T11-27-56_Phylo-VQVAE256img-phase5-speciesout/checkpoints/last.ckpt
# # yaml_path: /fastscratch/elhamod/logs/2022-11-07T11-27-56_Phylo-VQVAE256img-phase5-speciesout/configs/2022-11-07T11-27-56-project.yaml
# ckpt_path: /fastscratch/elhamod/logs/2022-11-11T02-12-49_Phylo-VQVAE256img-phase5-speciesout-final/checkpoints/last.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-11-11T02-12-49_Phylo-VQVAE256img-phase5-speciesout-final/configs/2022-11-11T02-12-49-project.yaml





# #without phylo
# ckpt_path: /home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/checkpoints/last.ckpt
# yaml_path: /home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/configs/2022-10-12T10-08-53-project.yaml

# # class weights
# ckpt_path: /home/elhamod/projects/taming-transformers/logs/imported/2022-11-05T19-12-52_Phylo-VQVAE512img-phase4-multiclass-lowerlr-8cblevel-stronganti-2layers-cyclical-classweighting/checkpoints/epoch=000068.ckpt
# yaml_path: /home/elhamod/projects/taming-transformers/logs/imported/2022-11-05T19-12-52_Phylo-VQVAE512img-phase4-multiclass-lowerlr-8cblevel-stronganti-2layers-cyclical-classweighting/configs/2022-11-05T19-12-52-project-infer.yaml

# nolastrelumlp
# ckpt_path: /fastscratch/elhamod/logs/2022-11-07T15-02-16_Phylo-VQVAE256img-phase5-nolastrelumlp/checkpoints/last.ckpt #epoch=000068.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-11-07T15-02-16_Phylo-VQVAE256img-phase5-nolastrelumlp/configs/2022-11-07T15-02-16-project.yaml




# ckpt_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/checkpoints/last.ckpt
# yaml_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/configs/2023-01-15T00-45-57-project.yaml

ckpt_path: /fastscratch/elhamod/logs/2023-01-31T15-12-29_Phylo-VQVAE-phase8256img-4phylo-4nonphylo-fewernonphylodim/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/2023-01-31T15-12-29_Phylo-VQVAE-phase8256img-4phylo-4nonphylo-fewernonphylodim/configs/2023-01-31T15-12-29-project.yaml


