size: 256
file_list_path:  /fastscratch/elhamod/data/Fish/fish_test.txt
unique_skipped_labels: []

DEVICE: 0
num_workers: 8
batch_size: 1 # DO NOT CHANGE! 

per_phylo_level: True # whether to calculate the histograms for ancestor levels as well

visualize_histograms: True # whether to plot the histpgrams

##############################

ckpt_path: /fastscratch/elhamod/logs/PhyloNN/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/PhyloNN/configs/2023-01-15T00-45-57-project.yaml

