size: 256
file_list_path: /fastscratch/elhamod/logs/2022-11-08T00-00-03_Phylo-VQVAE-transformer256img-phase4-originalVQGAN/generated/1012026_100_1.0/list.txt

DEVICE: 0
num_workers: 8
batch_size: 1 # DO NOT CHANGE! 

ckpt_path: /fastscratch/elhamod/logs/2023-01-09T18-13-38_Phylo-VQVAE-phase7256img-originalvqgan-imagenetbg-aug/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/2023-01-09T18-13-38_Phylo-VQVAE-phase7256img-originalvqgan-imagenetbg-aug/configs/2023-01-09T18-13-38-project.yaml