size: 256
file_list_path:  /fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt
unique_skipped_labels: []

DEVICE: 0
num_workers: 8
batch_size: 1 # DO NOT CHANGE! 

per_phylo_level: True # whether to calculate the histograms for ancestor levels as well

create_histograms: True # whether to plot the histpgrams

##############################

ckpt_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/configs/2023-01-15T00-45-57-project.yaml

