
DEVICE: 0

num_workers: 8
batch_size: 100


lr: 0.01
step_size: 25
num_epochs: 50
num_of_layers: 2

# encoding_model_config: /fastscratch/elhamod/logs/2022-12-21T16-52-48_Phylo-VQVAE-phase7256img-lowerbeta/configs/2022-12-21T16-52-48-project.yaml
# encoding_model_path: /fastscratch/elhamod/logs/2022-12-21T16-52-48_Phylo-VQVAE-phase7256img-lowerbeta/checkpoints/epoch=000302.ckpt

encoding_model_config: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/configs/2022-10-31T12-46-01-project-updated.yaml
encoding_model_path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/checkpoints/last.ckpt


# Just set phylogeny_path to None for training species level
phylogeny_path:
    


size: 256
file_list_path_train: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_train_padded_256.txt"
file_list_path_test: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256.txt"
# size= 512
# file_list_path = "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_512.txt"
# file_list_path: "/home/elhamod/data/Fish/taming_transforms_fish_test_small.txt" # Just for test

##############