size: 256
file_list_path:  /fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt

# species1: 'Lepomis megalotis'
species1: 'Noturus miurus'
# species1: 'Notropis percobromus'

# species2: 'Lepomis macrochirus'
species2: 'Notropis nubilus'
# species2: 'Noturus flavus'

DEVICE: 0

##############################

#Unseen species
ckpt_path: /fastscratch/elhamod/logs/2023-01-31T22-56-46_Phylo-VQVAE-phase8256img-4phylo-4nonphylo-fewernonphylodim-speciesout/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/2023-01-31T22-56-46_Phylo-VQVAE-phase8256img-4phylo-4nonphylo-fewernonphylodim-speciesout/configs/2023-01-31T22-56-46-project.yaml
