size: 256
# file_list_path: "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_256.txt"
file_list_path:  /fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt
# size= 512
# file_list_path = "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_512.txt"

species1: 'Morone chrysops'
species2: 'Morone mississippiensis'

distance_used: "js_divergence" #"chi2" 

DEVICE: 0

##############################

# # 256 combined nopass
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T10-40-42_Phylo-VQVAE256img-afterhyperp-combined/configs/2022-10-14T10-40-42-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T10-40-42_Phylo-VQVAE256img-afterhyperp-combined/checkpoints/last.ckpt"

# 4cbs
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/configs/2022-10-17T12-20-24-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/checkpoints/last.ckpt"

# anticlass 256
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-18T17-16-55_Phylo-VQVAE256img-afterhyperp-combined-anticlass/configs/2022-10-18T17-16-55-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-18T17-16-55_Phylo-VQVAE256img-afterhyperp-combined-anticlass/checkpoints/last.ckpt"

# 256 phylo-vqvae-phase2-morech-8cbperlevel
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-21T16-08-04_Phylo-VQVAE256img-phylo-vqvae-phase2-morech-8cbperlevel/configs/2022-10-21T16-08-04-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-21T16-08-04_Phylo-VQVAE256img-phylo-vqvae-phase2-morech-8cbperlevel/checkpoints/last.ckpt"

# 256 no phylo
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/configs/2022-10-12T10-08-53-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/checkpoints/last.ckpt"



#256 phase3-more fclayers
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-25T22-04-46_Phylo-VQVAE256img-phylo-vqvae-phase2-disentanglerconv-morefclayers/configs/2022-10-25T22-04-46-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-25T22-04-46_Phylo-VQVAE256img-phylo-vqvae-phase2-disentanglerconv-morefclayers/checkpoints/last.ckpt"

# # multiclass
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-multiclass-phase4/configs/2022-10-28T19-59-33-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-multiclass-phase4/checkpoints/epoch=000104.ckpt"

# multilabel
# yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-phase4/configs/2022-10-28T19-59-33-project.yaml"
# ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-28T19-59-33_Phylo-VQVAE512img-phylo-vqvae-phase2-morech-8cbperlevel-morenonattr-phase4/checkpoints/epoch=000362.ckpt"



# # 46ch
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/configs/2022-10-14T00-55-06-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/checkpoints/last.ckpt"


# slower lr
# yaml_path: "/fastscratch/elhamod/logs/2022-10-30T20-13-25_Phylo-VQVAE256img-phase4-swapconvin-nolastrelu-multiclass-lowerlr/configs/2022-10-30T20-13-25-project.yaml"
# ckpt_path: "/fastscratch/elhamod/logs/2022-10-30T20-13-25_Phylo-VQVAE256img-phase4-swapconvin-nolastrelu-multiclass-lowerlr/checkpoints/last.ckpt"

# ******slower lr stronganti
# ckpt_path: /home/elhamod/projects/taming-transformers/logs/imported/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/checkpoints/last.ckpt
# yaml_path: /home/elhamod/projects/taming-transformers/logs/imported/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/configs/2022-10-31T12-46-01-project.yaml

#without phylo
# ckpt_path: /home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/checkpoints/last.ckpt
# yaml_path: /home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/configs/2022-10-12T10-08-53-project.yaml


ckpt_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/configs/2023-01-15T00-45-57-project.yaml