size: 256
file_list_path: "/fastscratch/elhamod/data/Fish/fish_test.txt"

DEVICE: 0

top_k: 40

num_specimen_generated: 40
save_individual_images: True

outputdatasetdir: species_transfromer_generated
##############################

ckpt_path: /home/mridul/taming-transformers/logs/2023-02-02T18-56-56_CW-VQGAN-transformercw_imagenet_no_aug_base_model_transformer/checkpoints/last.ckpt
yaml_path: /home/mridul/taming-transformers/logs/2023-02-02T18-56-56_CW-VQGAN-transformercw_imagenet_no_aug_base_model_transformer/configs/2023-02-02T18-56-56-project.yaml