size: 256
file_list_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_train_padded_256.txt"
# size= 512
# file_list_path = "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_512.txt"

DEVICE: 0

top_k: 5

num_specimen_generated: 40
save_individual_images: True

outputdatasetdir: level0
##############################

# class weights
# ckpt_path: /fastscratch/elhamod/logs/2022-11-08T22-01-06_Phylo-VQVAE-transformer256img-phase4-level0/checkpoints/epoch=000611.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-11-08T22-01-06_Phylo-VQVAE-transformer256img-phase4-level0/configs/2022-11-08T22-01-06-project.yaml

# ckpt_path: /fastscratch/elhamod/logs/2022-11-10T02-23-47_Phylo-VQVAE-transformer256img-phase4-level0-finalstronger/checkpoints/last.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-11-10T02-23-47_Phylo-VQVAE-transformer256img-phase4-level0-finalstronger/configs/2022-11-10T02-23-47-project.yaml

ckpt_path: /fastscratch/elhamod/logs/2022-12-14T16-39-42_Phylo-VQVAE-transformer-phase7256img-phase7-level0/checkpoints/epoch=000848.ckpt
yaml_path: /fastscratch/elhamod/logs/2022-12-14T16-39-42_Phylo-VQVAE-transformer-phase7256img-phase7-level0/configs/2022-12-14T16-39-42-project.yaml