DEVICE: 0

##############################

ckpt_path: /fastscratch/elhamod/logs/vanilla_vqgan/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/vanilla_vqgan/configs/2023-01-09T18-13-38-project.yaml