path: /fastscratch/elhamod/logs/vanilla_vqgan/figs/results_summary # where to fine files in arrays1

file_name: "js-divergence to morpho"

output_names: [
  all,
]

arrays1: [
  js_divergence for phylo attributes heat_map.csv
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/ancestor_distance_level3 heat_map.csv,
]
