# path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/figs/results_summary
# path: /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary

# path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/figs/results_summary_species #***
# path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/figs/results_summary_level0
# path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/figs/results_summary_level1
# path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/figs/results_summary_level2
# path: /home/elhamod/projects/taming-transformers/analysis/baseline results

# path: /fastscratch/elhamod/projects/taming-transformers/logs/256pixels_256embedding/figs/results_summary

# path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/figs/results_summary

path: /fastscratch/elhamod/logs/2023-01-09T18-13-38_Phylo-VQVAE-phase7256img-originalvqgan-imagenetbg-aug/figs/results_summary

# file_name: "trimmed js-divergence to phylo"
file_name: "trimmed js-divergence to morpho"
# file_name: "trimmed baseline phylo"
# file_name: "trimmed baseline morpho"




# For phyloNN
output_names: [
  # non-attr to level3,
  # level0,
  # level1,
  # level2,
  all,
]

# For baselines
# output_names: [
#   LSF,
#   CW
# ]





# For phyloNN
arrays1: [
  # trimmed_js_divergence for non-attributes heat_map.csv,
  # trimmed_js_divergence for phylo attributes for level 0 heat_map.csv,
  # trimmed_js_divergence for phylo attributes for level 1 heat_map.csv,
  # trimmed_js_divergence for phylo attributes for level 2 heat_map.csv,
  trimmed_js_divergence for phylo attributes heat_map.csv
]

# For baselines
# arrays1: [
#   trimmed LSF distances.csv,
#   trimmed CW_distances.csv
# ]




# arrays2: [
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/zq hamming species distances for level 3 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/zq hamming species distances for level 0 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/zq hamming species distances for level 1 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/zq hamming species distances for level 2 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/zq hamming species distances for level 3 heat_map.csv
# ]
# arrays2: [
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/phylo species distances for level 3 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/phylo species distances for level 0 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/phylo species distances for level 1 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/phylo species distances for level 2 heat_map.csv,
#   /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary/phylo species distances for level 3 heat_map.csv,]

# arrays2: [
#   /home/elhamod/projects/taming-transformers/analysis/ancestor_distance_level3 heat_map.csv,
#   /home/elhamod/projects/taming-transformers/analysis/ancestor_distance_level0 heat_map.csv,
#   /home/elhamod/projects/taming-transformers/analysis/ancestor_distance_level1 heat_map.csv,
#   /home/elhamod/projects/taming-transformers/analysis/ancestor_distance_level2 heat_map.csv,
#   /home/elhamod/projects/taming-transformers/analysis/ancestor_distance_level3 heat_map.csv,
# ]


# arrays2: [
#   # /home/elhamod/projects/taming-transformers/analysis/phylo analysis/trimmed phylo species distances for level 3 heat_map.csv,
#   # /home/elhamod/projects/taming-transformers/analysis/phylo analysis/trimmed phylo species distances for level 0 heat_map.csv,
#   # /home/elhamod/projects/taming-transformers/analysis/phylo analysis/trimmed phylo species distances for level 1 heat_map.csv,
#   # /home/elhamod/projects/taming-transformers/analysis/phylo analysis/trimmed phylo species distances for level 2 heat_map.csv,
#   /home/elhamod/projects/taming-transformers/analysis/phylo analysis/trimmed phylo species distances for level 3 heat_map.csv,
# ]
arrays2: [
  # /home/elhamod/projects/taming-transformers/analysis/ancestor analysis/trimmed_ancestor_distance_level3 heat_map.csv,
  # /home/elhamod/projects/taming-transformers/analysis/ancestor analysis/trimmed_ancestor_distance_level0 heat_map.csv,
  # /home/elhamod/projects/taming-transformers/analysis/ancestor analysis/trimmed_ancestor_distance_level1 heat_map.csv,
  # /home/elhamod/projects/taming-transformers/analysis/ancestor analysis/trimmed_ancestor_distance_level2 heat_map.csv,
  /home/elhamod/projects/taming-transformers/analysis/ancestor analysis/trimmed_ancestor_distance_level3 heat_map.csv,
]

permute_array1: false
