path: /fastscratch/elhamod/logs/2022-11-04T15-27-23_Phylo-VQVAE256img-phase4-nophylo/figs/results_summary

file_name: "js-divergence to phylo"

output_names: [
  non-attr to phylo,
  level0,
  level1,
  level2,
  phylo,
]

arrays1: [
  js_divergence for non-attributes heat_map.csv,
  js_divergence for phylo attributes for level 0 heat_map.csv,
  js_divergence for phylo attributes for level 1 heat_map.csv,
  js_divergence for phylo attributes for level 2 heat_map.csv,
  js_divergence for phylo attributes heat_map.csv

]

# arrays2: [
#   zq hamming species distances for level 3 heat_map.csv,
#   zq hamming species distances for level 0 heat_map.csv,
#   zq hamming species distances for level 1 heat_map.csv,
#   zq hamming species distances for level 2 heat_map.csv,
#   zq hamming species distances for level 3 heat_map.csv
# ]

arrays2: [
  phylo species distances for level 3 heat_map.csv,
  phylo species distances for level 0 heat_map.csv,
  phylo species distances for level 1 heat_map.csv,
  phylo species distances for level 2 heat_map.csv,
  phylo species distances for level 3 heat_map.csv,
]
