path: /home/elhamod/projects/phylonn/results/PhyloNN/results_summary  # where to fine files in arrays1

file_name: "js-divergence to morpho"

output_names: [
  all,
]

arrays1: [
  js-divergence for phylo attributes heat_map.csv
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/level3.csv,
]
