path: /fastscratch/elhamod/logs/vanilla_vqgan/figs/results_summary # where to fine files in arrays1

file_name: "js-divergence to phylo"

output_names: [
  all,
]

arrays1: [
  js_divergence for phylo attributes heat_map.csv
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level3.csv,
]

