path: /home/elhamod/projects/phylonn/analysis/baseline results # where to fine files in arrays1
file_name: "baseline phylo"

output_names: [
  LSF,
  CW
]

arrays1: [
  LSF_distances.csv,
  CW_distances.csv
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level3.csv,
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level3.csv,
]