path: /home/elhamod/projects/phylonn/results/vanilla_vqgan/results_summary # where to fine files in arrays1

file_name: "js-divergence to phylo"

output_names: [
  all,
]

arrays1: [
  js-divergence.csv
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level3.csv,
]

