path: /home/elhamod/projects/phylonn/results/baselines/cosine distances # where to fine files in arrays1
file_name: "baseline morpho" # output file name

output_names: [
  LSF,
  CW
]

arrays1: [
  LSF.csv,
  CW.csv
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/level3.csv,
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/level3.csv,
]
