path: /home/elhamod/projects/phylonn/analysis/phylo analysis # where to fine files in arrays1

file_name: "phylo-to-morph-groundtruth"

output_names: [
  level0,
  level1,
  level2,
  level3
]

arrays1: [
  trimmed phylo species distances for level 0 heat_map.csv,
  trimmed phylo species distances for level 1 heat_map.csv,
  trimmed phylo species distances for level 2 heat_map.csv,
  trimmed phylo species distances for level 3 heat_map.csv,
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/trimmed_ancestor_distance_level0 heat_map.csv,
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/trimmed_ancestor_distance_level1 heat_map.csv,
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/trimmed_ancestor_distance_level2 heat_map.csv,
  /home/elhamod/projects/phylonn/analysis/ancestor analysis/trimmed_ancestor_distance_level3 heat_map.csv,
]