path: /fastscratch/elhamod/logs/PhyloNN/figs/results_summary # where to fine files in arrays1

file_name: "baseline phylo"

output_names: [
  non-attr to level3,
  level0,
  level1,
  level2,
  level3,
]

arrays1: [
  js_divergence for non-attributes heat_map.csv,
  js_divergence for phylo attributes for level 0 heat_map.csv,
  js_divergence for phylo attributes for level 1 heat_map.csv,
  js_divergence for phylo attributes for level 2 heat_map.csv,
  js_divergence for phylo attributes heat_map.csv
]

arrays2: [
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level3.csv,
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level0.csv,
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level1.csv,
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level2.csv,
  /home/elhamod/projects/phylonn/analysis/phylo analysis/level3.csv,
]
