
DEVICE: 0

num_workers: 8
batch_size: 200

load_model: CW


size: 256
file_list_path: "/fastscratch/elhamod/data/Fish/fish_test.txt"

ckpt_path: /fastscratch/mridul/kdd/cw_model/checkpoints/last.ckpt
yaml_path: /fastscratch/mridul/kdd/cw_model/configs/2023-02-02T13-37-50-project.yaml