
DEVICE: 0

num_workers: 8
batch_size: 200 #200 for tinkercliffs

load_model: CW


size: 256
# file_list_path: "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_256.txt"
file_list_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256.txt"

ckpt_path: /home/mridul/debug/taming-transformers/logs/2023-02-02T13-37-50_CW-VQVAE-debugcw_imagenet_no_aug_base_model_no_aug_lr_4.5/checkpoints/last.ckpt
yaml_path: /home/mridul/debug/taming-transformers/logs/2023-02-02T13-37-50_CW-VQVAE-debugcw_imagenet_no_aug_base_model_no_aug_lr_4.5/configs/2023-02-02T13-37-50-project.yaml