yaml_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/configs/2022-10-17T12-20-24-project.yaml"
ckpt_path: "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/checkpoints/last.ckpt"

imagepath: "/home/elhamod/data/Fish/train_padded_256/Notropis percobromus/INHS_FISH_76701.jpg"

size: 256
file_list_path: "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_256.txt"
# size= 512
# file_list_path = "/home/elhamod/data/Fish/taming_transforms_fish_train_padded_512.txt"

cummulative: True
plot_diff: False

DEVICE: 0
num_workers: 8
batch_size: 5



########################################

# best 256 with phylo   
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-07T12-09-20_Phylo-VQVAE256img-afterhyperp/configs/2022-10-07T12-09-20-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-07T12-09-20_Phylo-VQVAE256img-afterhyperp/checkpoints/last.ckpt"
# 256 with korthogonality
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-13T01-13-29_Phylo-VQVAE256img-afterhyperp-kernelorthogonality/configs/2022-10-13T01-13-29-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-13T01-13-29_Phylo-VQVAE256img-afterhyperp-kernelorthogonality/checkpoints/last.ckpt"
# 256 less channels
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-12T23-03-58_Phylo-VQVAE256img-afterhyperp-ch64/configs/2022-10-12T23-03-58-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-12T23-03-58_Phylo-VQVAE256img-afterhyperp-ch64/checkpoints/last.ckpt"
# 256 no pass through
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-12T23-04-18_Phylo-VQVAE256img-afterhyperp-nopassthrough/configs/2022-10-12T23-04-18-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-12T23-04-18_Phylo-VQVAE256img-afterhyperp-nopassthrough/checkpoints/last.ckpt"

# 256 without phylo
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/configs/2022-10-12T10-08-53-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-12T10-08-53_Phylo-VQVAE256img-afterhyperp-withoutphylo-round2/checkpoints/last.ckpt"

# # # 512 less channels
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T11-39-30_Phylo-VQVAE512img-afterhyperp/configs/2022-10-14T11-39-30-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T11-39-30_Phylo-VQVAE512img-afterhyperp/checkpoints/last.ckpt"

# # 256 combined
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/configs/2022-10-14T00-55-06-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/checkpoints/last.ckpt"

# # 512 combined no passthrough
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T11-39-39_Phylo-VQVAE512img-afterhyperp/configs/2022-10-14T11-39-39-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T11-39-39_Phylo-VQVAE512img-afterhyperp/checkpoints/last.ckpt"


# #256 combined 36ch
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-16T00-21-41_Phylo-VQVAE/configs/2022-10-16T00-21-41-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-16T00-21-41_Phylo-VQVAE/checkpoints/last.ckpt"

# # 256 combined nopass
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T10-40-42_Phylo-VQVAE256img-afterhyperp-combined/configs/2022-10-14T10-40-42-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T10-40-42_Phylo-VQVAE256img-afterhyperp-combined/checkpoints/last.ckpt"

# 4cbs
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/configs/2022-10-17T12-20-24-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-17T12-20-24_Phylo-VQVAE256img-afterhyperp-combined-4cbperlevel/checkpoints/last.ckpt"


# # 46ch
# yaml_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/configs/2022-10-14T00-55-06-project.yaml"
# ckpt_path = "/home/elhamod/projects/taming-transformers/logs/2022-10-14T00-55-06_Phylo-VQVAE256img-afterhyperp-combined/checkpoints/last.ckpt"

# anticlass
yaml_path: /home/elhamod/projects/taming-transformers/logs/2022-10-18T17-16-55_Phylo-VQVAE256img-afterhyperp-combined-anticlass/configs/2022-10-18T17-16-55-project.yaml
ckpt_path: /home/elhamod/projects/taming-transformers/logs/2022-10-18T17-16-55_Phylo-VQVAE256img-afterhyperp-combined-anticlass/checkpoints/last.ckpt


