ckpt_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/configs/2023-01-15T00-45-57-project.yaml

DEVICE: 0

image_index1: 3406 # 3407 # 3406 # /fastscratch/elhamod/data/Fish/train_padded_256_imagenetmeancolor/Notropis wickliffi/INHS_FISH_9981.jpg
image_index2: 3407 # 3406 # 3407# /fastscratch/elhamod/data/Fish/train_padded_256_imagenetmeancolor/Noturus exilis/INHS_FISH_100729.jpg

# image_index1: 656  #/fastscratch/elhamod/data/Fish/train_padded_256_imagenetmeancolor/Lepomis auritus/INHS_FISH_51429.jpg
# image_index2: 3781 #/fastscratch/elhamod/data/Fish/train_padded_256_imagenetmeancolor/Noturus miurus/INHS_FISH_11669.jpg

size: 256
file_list_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_train_padded_256_imagenetmeancolor.txt"

order: "entropy" #"entropy" #"reverse" # None, 
show_only_key_imgs: True #False #True
according_to_target: True

# phylogeny_path: "/home/elhamod/data/Fish"
# phyloDistances_string: "0.77,0.5,0.33"

bb_model_paths: [
  /home/elhamod/projects/taming-transformers/analysis/BBmodels/classification_model_0.path,
  /home/elhamod/projects/taming-transformers/analysis/BBmodels/classification_model_1.path,
  /home/elhamod/projects/taming-transformers/analysis/BBmodels/classification_model_2.path,
  /home/elhamod/projects/taming-transformers/analysis/BBmodels/classification_model_3.path
]

