ckpt_path: /fastscratch/mridul/kdd/cw_model/checkpoints/last.ckpt
yaml_path: /fastscratch/mridul/kdd/cw_model/configs/2023-02-02T13-37-50-project.yaml

DEVICE: 0

image_index1: 40
image_index2: 734
count: 15

model_name: 'CW'

size: 256
file_list_path: "/fastscratch/elhamod/data/Fish/fish_test.txt"

keyimgrate: 70

