
DEVICE: 0

num_workers: 8
batch_size: 32 #100

bb_model_path: analysis/BBmodels/classification_model_3.path

#naive bayes
# dataset_path: logs/imported/2022-11-05T19-12-52_Phylo-VQVAE512img-phase4-multiclass-lowerlr-8cblevel-stronganti-2layers-cyclical-classweighting/figs/generated_dataset/species

# dataset_path: /fastscratch/elhamod/logs/2022-11-10T02-23-40_Phylo-VQVAE-transformer256img-phase4-transformer-species-finalstronger/figs/transformer_generated_dataset/species

size: 256

file_name: "generated"
dataset_path: /fastscratch/elhamod/logs/2022-12-14T16-50-57_Phylo-VQVAE-transformer-phase7256img-phase7-level3/figs/transformer_generated_dataset/species
save_path: /fastscratch/elhamod/logs/2022-12-14T16-50-57_Phylo-VQVAE-transformer-phase7256img-phase7-level3/figs/transformer_generated_dataset/species

