
DEVICE: 0

num_workers: 8
batch_size: 32 #100

bb_model_path: analysis/BBmodels/classification_model_3.path

#naive bayes
# dataset_path: logs/imported/2022-11-05T19-12-52_Phylo-VQVAE512img-phase4-multiclass-lowerlr-8cblevel-stronganti-2layers-cyclical-classweighting/figs/generated_dataset/species
# dataset_path: /fastscratch/elhamod/logs/2022-11-10T02-23-40_Phylo-VQVAE-transformer256img-phase4-transformer-species-finalstronger/figs/transformer_generated_dataset/species

size: 256

file_name: "train"
dataset_path: /fastscratch/elhamod/data/Fish/train_padded_256
save_path: /home/elhamod/projects/taming-transformers/analysis/BBmodels/level3