
DEVICE: 0

num_workers: 8
batch_size: 32 #100

bb_model_path: analysis/classification_model_3.path

#naive bayes
# dataset_path: logs/imported/2022-11-05T19-12-52_Phylo-VQVAE512img-phase4-multiclass-lowerlr-8cblevel-stronganti-2layers-cyclical-classweighting/figs/generated_dataset/species

dataset_path: /fastscratch/elhamod/logs/2022-11-05T15-32-30_Phylo-VQVAE-transformer/figs/transformer_generated_dataset/species
size: 256