ckpt_path: /home/harishbabu/projects/phylonn/logs/LSF/checkpoints/last.ckpt
yaml_path: /home/harishbabu/projects/phylonn/logs/LSF/configs/2023-02-01T23-38-48-project.yaml

DEVICE: 0

# image_index1: 40
# image_index2: 734
# count: 15

# image_index1: 3763
# image_index2: 962
# count: 10

image_index1: 3390
image_index2: 3407
count: 15

size: 256
file_list_path: "/fastscratch/elhamod/data/Fish/fish_train.txt"


