DEVICE: 0

num_workers: 8
batch_size: 200

model_name: VQGAN

file_prefix: "vanilla-vqgan-test-set"

img_res: 256
dataset_path: "/fastscratch/elhamod/data/Fish/fish_test.txt"

ckpt_path: /fastscratch/elhamod/logs/vanilla_vqgan/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/vanilla_vqgan/configs/2023-01-09T18-13-38-project.yaml

# Just set phylogeny_path to None when not applicable
phylogeny_path: 
# level: 0
# phyloDistances_string: "0.77,0.5,0.33"
# phylogeny_path: /fastscratch/elhamod/data/Fish

phylogeny_knn: /fastscratch/elhamod/data/Fish

which_tsne_plots: ['standard', 'knn']
