DEVICE: 0

num_workers: 8
batch_size: 200

isOriginalVQGAN: true

model_type: 'lsf' # 'VQGAN', 'phyloNN'


file_prefix: "LSF-testing"
img_res: 256
dataset_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt"

ckpt_path: /home/harishbabu/projects/taming-transformers/logs/2023-02-01T23-38-48_LSF2-VQVAE1024emb-256img_imagenetmean_noaug-base_noaug_withimgnet/checkpoints/last.ckpt
yaml_path: /home/harishbabu/projects/taming-transformers/logs/2023-02-01T23-38-48_LSF2-VQVAE1024emb-256img_imagenetmean_noaug-base_noaug_withimgnet/configs/2023-02-01T23-38-48-project.yaml

# Just set phylogeny_path to None for training species level
phylogeny_path: 
# level: 0
# phyloDistances_string: "0.77,0.5,0.33"
# phylogeny_path: /fastscratch/elhamod/data/Fish

phylogeny_knn: /fastscratch/elhamod/data/Fish

which_tsne_plots: ['standard', 'images', 'knn'] #  
legend_labels: ['class']