DEVICE: 0

num_workers: 8
batch_size: 200

file_prefix: "tsne-generated"
img_res: 256
# dataset_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_train_padded_256.txt"
# dataset_path: "/fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256.txt"
# dataset_path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/figs/generated_dataset_2/list.txt
# dataset_path: /fastscratch/elhamod/logs/2023-01-06T13-27-07_Phylo-VQVAE-transformer-phase7256img-phase7-level3-lowerbeta2/generated/124200_5_1.0/list.txt
dataset_path: /fastscratch/elhamod/logs/2023-01-28T17-44-33_Phylo-VQVAE-transformer-phase8256img-phase8-4phylo-4nonphylo-idea1-lvl3/figs/transformer_generated_dataset/taming_transforms_fish_test_padded_512.txt  

# # slower lr stronganti
# ckpt_path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/checkpoints/last.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-10-31T12-46-01_Phylo-VQVAE256img-phase4-multiclass-lowerlr-8cblevel-stronganti/configs/2022-10-31T12-46-01-project-updated.yaml


# #lower beta
# ckpt_path: /fastscratch/elhamod/logs/2022-12-21T16-52-48_Phylo-VQVAE-phase7256img-lowerbeta/checkpoints/epoch=000302.ckpt
# yaml_path: /fastscratch/elhamod/logs/2022-12-21T16-52-48_Phylo-VQVAE-phase7256img-lowerbeta/configs/2022-12-21T16-52-48-project.yaml


ckpt_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/checkpoints/last.ckpt
yaml_path: /fastscratch/elhamod/logs/2023-01-15T00-45-57_Phylo-VQVAE-phase8256img-4phylo-4nonphylo/configs/2023-01-15T00-45-57-project.yaml

# Just set phylogeny_path to None for training species level
# phylogeny_path: 
level: 2
phyloDistances_string: "0.77,0.5,0.33"
phylogeny_path: /fastscratch/elhamod/data/Fish

which_tsne_plots: ['knn'] #[ 'standard', 'images'] #, 'incorrect' 
legend_labels: ['class']