DEVICE: 0

num_workers: 8
batch_size: 200

model_name: CW

file_prefix: "CW"
img_res: 256
dataset_path: "/fastscratch/elhamod/data/Fish/fish_test.txt"

ckpt_path: /fastscratch/mridul/kdd/cw_model/checkpoints/last.ckpt
yaml_path: /fastscratch/mridul/kdd/cw_model/configs/2023-02-02T13-37-50-project.yaml


# Just set phylogeny_path to None when not applicable
# phylogeny_path: None

phylogeny_knn: /fastscratch/elhamod/data/Fish

which_tsne_plots: ['standard', 'knn']
legend_labels: ['class']