DEVICE: 0

num_workers: 8
batch_size: 200

model_name: 'LSF'

file_prefix: "LSF-test-set"
img_res: 256
dataset_path: "/fastscratch/elhamod/data/Fish/fish_test.txt"

ckpt_path: /home/harishbabu/projects/phylonn/logs/LSF/checkpoints/last.ckpt
yaml_path: /home/harishbabu/projects/phylonn/logs/LSF/configs/2023-02-01T23-38-48-project.yaml

phylogeny_knn: /fastscratch/elhamod/data/Fish

which_tsne_plots: ['standard', 'knn']
legend_labels: ['class']
