model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  project: CUB-VQGAN
  params:
    embed_dim: 256
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 20
    num_workers: 8
    train:
      target: taming.data.cub_dataloader.CUBTrain
      params:
        training_images_list_file: /fastscratch/mridul/cub_190_split_resized/official/CUB_200_2011/original_images_train.txt
        size: 256
        add_labels: True
    validation:
      target: taming.data.cub_dataloader.CUBTest
      params:
        test_images_list_file: /fastscratch/mridul/cub_190_split_resized/official/CUB_200_2011/original_images_test.txt
        size: 256
        add_labels: True

