model:
  base_learning_rate: 4.5e-6 #we tried 4.5e-3 #4.5e-6
  target: scripts.models.cwautoencoder.CWmodelVQGAN
  # target: scripts.models.vqgan.VQModel
  project: CW-VQGAN
  params:
    ckpt_path: ./logs/256pixels_256embedding/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 1024
    cw_module_transformers: False
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
    # lossconfig:
    #   target: scripts.modules.losses.DummyLoss

    # phylomodel_params:
    #   embed_dim: 16
    #   n_embed: 64
    #   #
    #   n_phylolevels: 4
    #   codebooks_per_phylolevel: 4
    #   #
    #   n_phylo_channels: 32 # tried 1 #32
    #   # NOT hyperparameters.
    #   resolution: 16
    #   in_channels: 256
    #   out_ch: 256
    #   ch: 256
    #   #ch_mult: [ 1]  # num_down = len(ch_mult)-1
    #   # num_res_blocks: 2
    #   # attn_resolutions: [16]

    lossconfig:
      target: scripts.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

    concept_data:
      target: main.DataModuleFromConfig
      params:
        batch_size: 30
        num_workers: 8
        train:
          target: scripts.data.custom.CustomTrain
          params:
            training_images_list_file: /home/mridul/data/phylo-VQVAE/fish_train_padded_256.txt
            size: 256
            add_labels: True
        validation:
          target: scripts.data.custom.CustomTest
          params:
            test_images_list_file: /home/mridul/data/phylo-VQVAE/fish_test_padded_256.txt
            size: 256
            add_labels: True



data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: scripts.data.custom.CustomTrain
      params:
        training_images_list_file: /home/mridul/data/phylo-VQVAE/fish_train_padded_256.txt
        size: 256
        add_labels: True
    validation:
      target: scripts.data.custom.CustomTest
      params:
        test_images_list_file: /home/mridul/data/phylo-VQVAE/fish_test_padded_256.txt
        size: 256
        add_labels: True

# lightning:
#   trainer:
#     # max_steps: 10 
#     # limit_train_batches: 10
#     # limit_val_batches: 10
#     # fast_dev_run: false
#     profiler: advanced #simple


