model:
  base_learning_rate: 4.5e-6 #we tried 4.5e-3 #4.5e-6
  target: scripts.models.LSFautoencoder.LSFVQVAE
  project: LSF-VQVAE
  params:
    ckpt_path: /home/harishbabu/data/Fish/phylo-VQVAE/512pixels_256embedding/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
    lossconfig:
      target: scripts.modules.losses.DummyLoss
          
        
    LSF_params:
      # image_size, label_size, nf, hidden_size=None, nc=3
      learning_rate: 5.0e-4 # orginially 1e-4
      image_size: 32 # not the actual image, input from the base encoder to distangler (256x32x32)
      label_size: 38
      nf: 256
      hidden_size: 1024
      nc: 256
      

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: scripts.data.custom.CustomTrain
      params:
        training_images_list_file: /home/harishbabu/data/Fish/phylo-VQVAE/taming_transforms_fish_train_padded_512.txt
        size: 512
        add_labels: true
    validation:
      target: scripts.data.custom.CustomTest
      params:
        test_images_list_file: /home/harishbabu/data/Fish/phylo-VQVAE/taming_transforms_fish_test_padded_512.txt
        size: 512
        add_labels: true

# lightning:
#   trainer:
#     # max_steps: 10 
#     # limit_train_batches: 10
#     # limit_val_batches: 10
#     # fast_dev_run: false
#     profiler: advanced #simple

lightning:
  trainer:
    max_epochs: 200
    # max_steps: 10
    # limit_train_batches: 10
    # limit_val_batches: 10
    # fast_dev_run: false
    profiler: advanced #simple
