model:
  base_learning_rate: 4.5e-6 #we tried 4.5e-3 #4.5e-6
  target: scripts.models.cwautoencoder.CWmodelVQGAN_baseline
  # target: scripts.models.vqgan.VQModel
  project: CW-VQVAE
  params:
    ckpt_path: ./logs/256pixels_256embedding/checkpoints/last.ckpt
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
    lossconfig:
      target: scripts.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

    concept_data:
      target: main.DataModuleFromConfig
      params:
        batch_size: 100
        num_workers: 8
        train:
          target: scripts.data.custom.CustomTrain
          params:
            training_images_list_file: /home/mridul/data/phylo-VQVAE/taming_transforms_fish_train_padded_256.txt
            size: 256
            add_labels: True
        validation:
          target: scripts.data.custom.CustomTest
          params:
            test_images_list_file: /home/mridul/data/phylo-VQVAE/taming_transforms_fish_test_padded_256.txt
            size: 256
            add_labels: True
        

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: scripts.data.custom.CustomTrain
      params:
        training_images_list_file: /home/mridul/data/phylo-VQVAE/taming_transforms_fish_train_padded_256.txt
        size: 256
    validation:
      target: scripts.data.custom.CustomTest
      params:
        test_images_list_file: /home/mridul/data/phylo-VQVAE/taming_transforms_fish_test_padded_256.txt
        size: 256

