model:
  base_learning_rate: 4.5e-06
  project: CW-VQGAN-transformer
  target: scripts.models.cond_transformer.Net2NetTransformer
  params:
    cond_stage_key: class
    transformer_config:
      target: scripts.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 257
        n_layer: 5
        n_head: 16
        n_embd: 1024
    first_stage_config:
      target: scripts.models.cwautoencoder.CWmodelVQGAN
      project: CW-VQGAN
      params:
        ckpt_path: /fastscratch/mridul/kdd/cw_model_transformer/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        cw_module_transformers: True
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: scripts.modules.losses.DummyLoss
        concept_data:
          target: main.DataModuleFromConfig
          params:
            batch_size: 20
            num_workers: 8
            train:
              target: scripts.data.custom.CustomTrain
              params:
                training_images_list_file: /fastscratch/elhamod/data/Fish/fish_train.txt
                size: 256
                add_labels: True
            validation:
              target: scripts.data.custom.CustomTest
              params:
                test_images_list_file: /fastscratch/elhamod/data/Fish/fish_test.txt
                size: 256
                add_labels: True
    cond_stage_config:
      target: scripts.modules.misc.label_conditioner.LabelCond


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: scripts.data.custom.CustomTrain
      params:
        training_images_list_file: /fastscratch/elhamod/data/Fish/fish_train.txt
        size: 256
        add_labels: True
    validation:
      target: scripts.data.custom.CustomTest
      params:
        test_images_list_file: /fastscratch/elhamod/data/Fish/fish_test.txt
        size: 256
        add_labels: True