model:
  base_learning_rate: 4.5e-06
  project: CW-VQGAN-transformer
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    cond_stage_key: class
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024 # size of codebook (number of possible codes)
        block_size: 257 # 256 attr+1 cond# codes predicted at once.
        n_layer: 5
        n_head: 16 # relationships to learn
        n_embd: 1024 #embedding dimensions for transformer. Does not have to be same as codebook but Ill pick same
    first_stage_config:
      target: taming.models.cwautoencoder.CWmodelVQGAN
      project: CW-VQVAE-debug
      params:
        ckpt_path: /home/mridul/debug/taming-transformers/logs/2023-02-02T13-37-50_CW-VQVAE-debugcw_imagenet_no_aug_base_model_no_aug_lr_4.5/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        cw_module_transformers: True
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
        concept_data:
          target: main.DataModuleFromConfig
          params:
            batch_size: 2
            num_workers: 8
            train:
              target: taming.data.custom.CustomTrain
              params:
                training_images_list_file: /fastscratch/elhamod/data/Fish/taming_transforms_fish_train_padded_256_imagenetmeancolor.txt
                size: 256
                add_labels: True
            validation:
              target: taming.data.custom.CustomTest
              params:
                test_images_list_file: /fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt
                size: 256
                add_labels: True
    cond_stage_config:
      target: taming.modules.misc.label_conditioner.LabelCond
      # params:
      #   num_of_classes: 38

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /fastscratch/elhamod/data/Fish/taming_transforms_fish_train_padded_256_imagenetmeancolor.txt
        size: 256
        add_labels: True
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /fastscratch/elhamod/data/Fish/taming_transforms_fish_test_padded_256_imagenetmeancolor.txt
        size: 256
        add_labels: True