model:
  base_learning_rate: 4.5e-06
  project: CW-VQGAN
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    cond_stage_key: class
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024 # size of codebook (number of possible codes)
        block_size: 257 # 256 attr+1 cond# codes predicted at once.
        n_layer: 5
        n_head: 16 # relationships to learn
        n_embd: 1024 #embedding dimensions for transformer. Does not have to be same as codebook but Ill pick same
    first_stage_config:
      # target: taming.models.vqgan.VQModel
      target: taming.models.cwautoencoder.CWmodelVQGAN
      project: CW-VQVAE
      params:
        # ckpt_path: ./logs/256pixels_256embedding/checkpoints/last.ckpt
        ckpt_path: ./logs/2022-11-07T12-10-33_CW-VQVAE256img-tinker-cw-model/checkpoints/last.ckpt
        embed_dim: 256
        n_embed: 1024
        cw_module_transformers: True
        ddconfig:
          double_z: False
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
        # lossconfig:
        #   target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
        #   params:
        #     disc_conditional: False
        #     disc_in_channels: 3
        #     disc_start: 10000
        #     disc_weight: 0.8
        #     codebook_weight: 1.0
        concept_data:
          target: main.DataModuleFromConfig
          params:
            batch_size: 2
            num_workers: 8
            train:
              target: taming.data.custom.CustomTrain
              params:
                training_images_list_file: /home/mridul/data/phylo-VQVAE/taming_transforms_fish_train_padded_256.txt
                size: 256
                add_labels: True
            validation:
              target: taming.data.custom.CustomTest
              params:
                test_images_list_file: /home/mridul/data/phylo-VQVAE/taming_transforms_fish_test_padded_256.txt
                size: 256
                add_labels: True
    cond_stage_config:
      target: taming.modules.misc.label_conditioner.LabelCond
      params:
        num_of_classes: 38

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /home/mridul/data/phylo-VQVAE/taming_transforms_fish_train_padded_256.txt
        size: 256
        add_labels: True
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: //home/mridul/data/phylo-VQVAE/taming_transforms_fish_test_padded_256.txt
        size: 256
        add_labels: True